###############################################################################
#  Z-shell configuration – Starship for iTerm2
###############################################################################

# ── Colours ──────────────────────────────────────────────────────────────────
export COLORTERM=truecolor         # Advertise 24-bit colour to capable emulators

# ── Starship prompt ──────────────────────────────────────────────────────────
eval "$(starship init zsh)"

# ── History behaviour ────────────────────────────────────────────────────────
export HISTFILE=~/.zsh_history
export HISTSIZE=50000
export SAVEHIST=50000
setopt SHARE_HISTORY          # Share history across sessions (implies append + inc-append)
setopt HIST_IGNORE_ALL_DUPS   # Drop older duplicate commands
setopt HIST_IGNORE_SPACE      # Don't record commands starting with a space
setopt HIST_VERIFY            # Show expanded history before running (safer !!)
setopt HIST_REDUCE_BLANKS     # Trim superfluous whitespace before saving

# ── Completion system ────────────────────────────────────────────────────────
# Must run BEFORE plugins so `compdef` is defined when ohmyzsh plugins load it.
autoload -Uz compinit
compinit

# ── Z-init / zsh-plugin-manager ──────────────────────────────────────────────
# Prefer the static bundle generated by bootstrap.sh (faster startup);
# fall back to dynamic load for machines that haven't run bootstrap yet.
if [[ -f ~/.zsh_plugins.sh ]]; then
    source ~/.zsh_plugins.sh
else
    source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
    antidote load
fi

# ── PATH (consolidated) ──────────────────────────────────────────────────────
# Homebrew's shellenv (sourced from .zprofile) already adds /opt/homebrew/bin.
typeset -U path   # dedupe PATH entries automatically
path=(
    "$HOME/.local/bin"
    "$HOME/bin"
    "$HOME/.yarn/bin"
    "$HOME/.config/yarn/global/node_modules/.bin"
    "$HOME/.bun/bin"
    "$HOME/.lmstudio/bin"
    "$HOME/.antigravity/antigravity/bin"
    "$HOME/Library/Android/sdk/emulator"
    "$HOME/Library/Android/sdk/tools"
    "$HOME/Library/Android/sdk/tools/bin"
    "$HOME/Library/Android/sdk/platform-tools"
    $path
)

export ANDROID_HOME="$HOME/Library/Android/sdk"
export BUN_INSTALL="$HOME/.bun"
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# ── Misc env vars ────────────────────────────────────────────────────────────
COREPACK_ENABLE_AUTO_PIN=0

# ── mise (version management) ────────────────────────────────────────────────
eval "$(/opt/homebrew/bin/mise activate zsh)"

# ── iTerm2 shell integration ─────────────────────────────────────────────────
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# ── fzf ──────────────────────────────────────────────────────────────────────
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
