###############################################################################
#  Z-shell configuration – Starship for iTerm2
###############################################################################

# ── Homebrew environment tweaks ──────────────────────────────────────────────
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_BUNDLE_FILE="$HOME/dotfiles/Brewfile"

# ── Colours ──────────────────────────────────────────────────────────────────
export COLORTERM=truecolor         # Advertise 24-bit colour to capable emulators

# ── Starship prompt ──────────────────────────────────────────────────────────
eval "$(starship init zsh)"

# ── History behaviour ────────────────────────────────────────────────────────
export HISTFILE=~/.zsh_history
export HISTSIZE=50000
export SAVEHIST=50000
setopt SHARE_HISTORY          # Share history across sessions (implies append + inc-append)
setopt HIST_IGNORE_ALL_DUPS   # Drop older duplicate commands
setopt HIST_IGNORE_SPACE      # Don't record commands starting with a space
setopt HIST_VERIFY            # Show expanded history before running (safer !!)
setopt HIST_REDUCE_BLANKS     # Trim superfluous whitespace before saving

# ── Completion system ────────────────────────────────────────────────────────
# Must run BEFORE plugins so `compdef` is defined when ohmyzsh plugins load it.
autoload -Uz compinit
compinit

# ── Z-init / zsh-plugin-manager ──────────────────────────────────────────────
# Prefer the static bundle generated by bootstrap.sh (faster startup);
# fall back to dynamic load for machines that haven't run bootstrap yet.
if [[ -f ~/.zsh_plugins.sh ]]; then
    source ~/.zsh_plugins.sh
else
    source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
    antidote load
fi

# ── PATH (consolidated) ──────────────────────────────────────────────────────
typeset -U path   # dedupe PATH entries automatically
if [[ -x /opt/homebrew/bin/brew ]]; then
    homebrew_prefix="/opt/homebrew"
elif [[ -x /usr/local/bin/brew ]]; then
    homebrew_prefix="/usr/local"
fi

path=(
    ${homebrew_prefix:+$homebrew_prefix/bin}
    ${homebrew_prefix:+$homebrew_prefix/sbin}
    "$HOME/.local/bin"
    "$HOME/bin"
    "$HOME/.yarn/bin"
    "$HOME/.config/yarn/global/node_modules/.bin"
    "$HOME/.bun/bin"
    "$HOME/.lmstudio/bin"
    "$HOME/.antigravity/antigravity/bin"
    "$HOME/Library/Android/sdk/emulator"
    "$HOME/Library/Android/sdk/tools"
    "$HOME/Library/Android/sdk/tools/bin"
    "$HOME/Library/Android/sdk/platform-tools"
    "/opt/homebrew/share/google-cloud-sdk/bin"
    $path
)
unset homebrew_prefix

export ANDROID_HOME="$HOME/Library/Android/sdk"
export BUN_INSTALL="$HOME/.bun"
[[ -s "$HOME/.bun/_bun" ]] && source "$HOME/.bun/_bun"

# ── Misc env vars ────────────────────────────────────────────────────────────
COREPACK_ENABLE_AUTO_PIN=0
export MANPAGER="sh -c 'col -bx | bat -l man -p'"   # bat-powered man pages
export BAT_THEME="Monokai Extended"

# ── Tool integrations ────────────────────────────────────────────────────────
eval "$(/opt/homebrew/bin/mise activate zsh)"
eval "$(atuin init zsh --disable-up-arrow)"
# First up press → recall last command; second up press → atuin search
_atuin_smart_up() {
  if [[ "$LASTWIDGET" == "_atuin_smart_up" && -n "$BUFFER" ]]; then
    zle _atuin_search_widget
  else
    zle up-line-or-history
  fi
}
zle -N _atuin_smart_up
bindkey '^[[A' _atuin_smart_up   # Up arrow
bindkey '^[OA' _atuin_smart_up   # Up arrow (application mode)
eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"

# ── Aliases ──────────────────────────────────────────────────────────────────
# eza (modern ls replacement)
alias ls='eza --icons --group-directories-first'
alias ll='eza -l --icons --git --group-directories-first'
alias la='eza -la --icons --git --group-directories-first'
alias lt='eza --tree --level=2 --icons --git-ignore'

# ── Deferred (non-critical, speeds up shell startup) ─────────────────────────
if (( $+functions[zsh-defer] )); then
    zsh-defer source "${HOME}/.iterm2_shell_integration.zsh" 2>/dev/null
    zsh-defer source ~/.fzf.zsh 2>/dev/null
else
    [[ -f "${HOME}/.iterm2_shell_integration.zsh" ]] && source "${HOME}/.iterm2_shell_integration.zsh"
    [[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
fi
